dryRun: false

extraArgs: {}

conditions: {}

replicaCount: 1

image:
  repository: planetlabs/draino
  tag: 5e07e93
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Add these annotations to all pods
podAnnotations: {}
  # name: value
  # prometheus.io/scrape: 'true'
  # prometheus.io/port: '9102'

# Add these labels to all pods
podLabels: {}
  # name: value

rbac:
  create: true
  serviceAccountName:

nodeSelector: {}

tolerations: []

affinity: {}
